[tasks.frontend-build]
command = "npm"
args = ["--prefix", "./app", "run", "build"]

[tasks.backend-build]
command = "cargo"
args = ["build", "--release"]

[tasks.frontend-test]
command = "npm"
args = ["--prefix", "./app", "test"]

[tasks.backend-test]
command = "cargo"
args = ["test"]

[tasks.build]
dependencies = [
    "frontend-build",
    "backend-build"
]

[tasks.test]
dependencies = [
    "frontend-test",
    "backend-test"
]